name: Test

on:
  workflow_dispatch:  
  schedule:
    - cron: "0 0 * * 0"  

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Work
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}  
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}  
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}  
          destination-folder: "solutions" 
          verbose: true
